
services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: robert
      MYSQL_PASSWORD: robert
      MYSQL_ROOT_PASSWORD: robert
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wordpress_network

  wordpress:
    image: robertcieplinksi/projekt_1:latest
    container_name: wordpress_app
    depends_on:
      - mysql
    restart: unless-stopped
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306 # mysql container name
      WORDPRESS_DB_USER: robert
      WORDPRESS_DB_PASSWORD: robert
      WORDPRESS_DB_NAME: wordpress
    volumes:
      - ~/wordpress/projekt_1:/var/www/html/wp-content
    networks:
      - wordpress_network
      - nginx-proxy_internal-net

volumes:
  db_data:
networks:
  wordpress_network:
    driver: bridge
  nginx-proxy_internal-net:
    external: true


